### ISSUE TITLE
Roberta-base

### ISSUE THREAD

**Issue by lolofo** [chijames/structured_dialogue_discourse_parsing#2]
Hello,

I'm trying to run your script to train on molweni.

In the training script, there is a parser for the roberta model.
This parser is set to ../roberta_base, which means that you have locally a roberta model.
How can we have access to your roberta-model ?

Loïc.

**Comment by chijames** [comment]
Hi Loïc,

You need to download the roberta model files from the [model hub](https://huggingface.co/roberta-base/tree/main) on huggingface and save the files in a folder named roberta_base.

Thanks,
Ta-Chung.

**Comment by lolofo** [comment]
Thanks a lot for the answer !
