### ISSUE TITLE
On the prediction of the graph

### ISSUE THREAD

**Issue by lolofo** [chijames/structured_dialogue_discourse_parsing#4]
Hello,

In the line 86 of the main, there is : 
d = set([(dd, idx+1) for idx, dd in enumerate(d[1:])]) # skip -1

I don't understand the format of the output graph. Why isn't it : 
d = set([(dd, **d[idx+1]**) for idx, dd in enumerate(d[1:])]) # skip -1

**Comment by chijames** [comment]
Hi,

Because it means there is a link that connects dd and idx+1. Both dd and idx+1 represent the indices of the utterances. In other words, the i-th element of d represent the link that connects the i-th utterance and d[i]-th utterance.
